# Generated by Django 5.1.6 on 2025-02-16 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRM',
            fields=[
                ('crm_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('enquiry_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_enquiry', models.DateField()),
                ('lead_source', models.CharField(blank=True, max_length=255, null=True)),
                ('travel_advisor', models.CharField(blank=True, max_length=255, null=True)),
                ('domestic_intl', models.CharField(blank=True, max_length=100, null=True)),
                ('enquiry_type', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_first_name', models.CharField(max_length=255)),
                ('customer_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_location', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_role', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('trip_from', models.CharField(max_length=255)),
                ('trip_to', models.CharField(max_length=255)),
                ('pax', models.IntegerField(default=1)),
                ('adult', models.IntegerField(default=1)),
                ('kid', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=1)),
                ('other_destinations', models.TextField(blank=True, null=True)),
                ('flight_class', models.CharField(blank=True, max_length=50, null=True)),
                ('flight_stopovers', models.CharField(blank=True, max_length=255, null=True)),
                ('hotel_type', models.CharField(blank=True, max_length=255, null=True)),
                ('room_sharing', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flight_name', models.CharField(blank=True, max_length=255, null=True)),
                ('flight_cost_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flight_total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hotel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hotel_cost_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hotel_total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('land_package_name', models.CharField(blank=True, max_length=255, null=True)),
                ('land_cost_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('land_total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flight_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('flight_margin_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hotel_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hotel_margin_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('land_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('land_margin_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_flight_cost_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selling_flight_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selling_hotel_cost_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selling_hotel_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selling_land_cost_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selling_land_total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_landing_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_package', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('margin_for_package', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('margin_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('working_space_notes', models.TextField(blank=True, null=True)),
                ('itinerary_file_base64', models.TextField(blank=True, null=True)),
                ('trip_name', models.CharField(blank=True, max_length=255, null=True)),
                ('next_follow_up_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
