# Generated by Django 5.1.6 on 2025-02-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
