# Generated by Django 5.1.6 on 2025-02-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_crm_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm',
            name='Status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
